### ISSUE TITLE
Incorrect command format

### ISSUE THREAD

**Issue by egorafanasenko** [sMitea/sdk-r2000#1]
Hey, 

could you clarify where did you get the command format for the R2000 module? Cause the one that you use right now doesn't work for our r2000 module.

thanks!

**Comment by smitea** [comment]
I'm so sorry, i can't help you, that my project's title mislead you. 
This project is about a data protocol of a Chinese RFID manufacture. 
So, nothing conerns about Impinj's official protocol.

If you want to use  Impinj R2000, you should read the manual of the  R2000 chip, 
and I'm not a hardware engineer,  sorry.

https://support.impinj.com/hc/en-us/articles/204969718 

This document may help you.

**Comment by smitea** [comment]
@egorafanasenko

**Comment by egorafanasenko** [comment]
thanks!
